baseURL = "https://zhangfelix.github.io"
languageCode = "zh-CN"
title = "My New Hugo Site"
theme = "dream"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true
googleAnalytics = "UA-98295641-1"
disqusShortname = "https-zhangfelix-github-io"

[params]
  # background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Nan"
  description = "g1eny0ung的生活记录～"
  avatar = "/global/avatar.jpg"
  motto = "一些信息"

  email = "zhn.i@hotmail.com"
  twitter = "zhangnfelix"
  # facebook = "..."
  # instagram = "..."
  # linkedin = "..."
  github = "zhangfelix"
  # stackoverflow = "..."
  # codepen = "..."

  siteStartYear = 2020

  favicon = "/global/favicon.ico"

