baseURL = "https://www.zhangfelix.com"
languageCode = "zh-CN"
title = "独白"
theme = "dream"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableRobotsTXT = true
googleAnalytics = "UA-169268545-1"
disqusShortname = "zhangfelix-blog"

[params]
  # background = "black"
  backgroundImage = "/global/background.jpg"
  linkColor = "seagreen"

  author = "Felix"
  description = "我的声音"
  avatar = "/global/avatar.jpg"
  motto = "Monologue"

  email = "zhn.i@hotmail.com"
  twitter = "zhangnfelix"
  # facebook = "..."
  # instagram = "..."
  # linkedin = "..."
  github = "zhangfelix"
  # stackoverflow = "..."
  # codepen = "..."

  siteStartYear = 2020

  favicon = "/global/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true